# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0f7996c4fbf6fbd58c562b28a7229cd66234e7f9eeefd8cff7fb014505eb35449258bd552f94a5d05009b233f4ce98cd297a303793a52c1949665526aaf55c7

test:
  secret_key_base: e7e721ed88473032483ceb67357cee94c52356309df2697840d1bf15b3475fa8044df50567713ff75ea28d681e4e300b7c666b983718af7e4b7db0c0fd28cc89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
